[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:494 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:499 Cutting network for postgresql/1
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:505 checking for no connectivity between postgresql/1 and postgresql/2
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:505 checking for no connectivity between postgresql/1 and postgresql/3
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:512 checking for no connectivity between postgresql/1 and the controller
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:519 checking whether the connectivity to the database is not working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:525 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:528 checking whether a new primary was elected
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:535 Restoring network for postgresql/1
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:539 waiting for cluster to become idle
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/1 [idle] active: Primary
  postgresql/2 [idle] active: Primary
  postgresql/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  postgresql/1 [idle] active: 
  postgresql/3 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:544 waiting for the database service to be ready on postgresql/1
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:548 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:199 checking that the former primary is now a replica
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:205 checking that all units are part of the same cluster
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:219 checking that no writes to the database were missed after stopping the writes
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:223 checking that the former primary is up to date with the cluster after restarting
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  02:16:41Z

App                  Version  Status  Scale  Charm                Channel      Rev  Exposed  Message
postgresql           14.12    active      3  postgresql                          0  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  190  no       received database credentials of the first database

Unit                    Workload  Agent  Machine  Public address  Ports     Message
postgresql-test-app/0*  active    idle   3        10.180.254.101            received database credentials of the first database
postgresql/1            active    idle   1        10.180.254.181  5432/tcp  
postgresql/2*           active    idle   2        10.180.254.100  5432/tcp  Primary
postgresql/3            active    idle   4        10.180.254.117  5432/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
1        started  10.180.254.181  juju-583602-1  ubuntu@22.04      Running
2        started  10.180.254.100  juju-583602-2  ubuntu@22.04      Running
3        started  10.180.254.101  juju-583602-3  ubuntu@22.04      Running
4        started  10.180.254.117  juju-583602-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-2: 01:31:44 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:31:44 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:31:44 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:31:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:31:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:31:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:31:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:31:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:31:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:31:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:31:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:41:32 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:41:32 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-3: 01:41:32 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-2: 01:49:21 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

machine-4: 02:05:02 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-4: 02:05:05 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-4" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: network is unreachable
machine-4: 02:05:09 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-4" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: network is unreachable
machine-4: 02:05:13 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-4" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: network is unreachable
machine-1: 02:14:17 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-1: 02:14:23 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:14:29 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:14:35 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:14:42 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:14:51 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:15:00 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:15:12 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host
machine-1: 02:15:25 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [0a7ee8] "machine-1" cannot open api: unable to connect to API: dial tcp 10.180.254.29:17070: connect: no route to host

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...