{"uid":"f61c3715f4b330f9","name":"test_user_with_extra_roles","fullName":"tests.integration.new_relations.test_new_relations#test_user_with_extra_roles","historyId":"51a0ff7ec809cc2830c84a70c26754af","time":{"start":1725501365751,"stop":1725501365931,"duration":180},"description":"Test superuser actions and the request for more permissions.","descriptionHtml":"<p>Test superuser actions and the request for more permissions.</p>\n","status":"broken","statusMessage":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 241, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 63, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 65, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 833, in _runtest_for\n    yield\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 878, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 183, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 173, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1632, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 162, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/tests/integration/new_relations/test_new_relations.py\", line 191, in test_user_with_extra_roles\n    connection_string = await build_connection_string(\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/tests/integration/new_relations/helpers.py\", line 50, in build_connection_string\n    if secret_uri := await get_application_relation_data(\n  File \"/home/runner/work/test-runners-2-github-x64-postgresql-operator/test-runners-2-github-x64-postgresql-operator/tests/integration/new_relations/helpers.py\", line 211, in get_application_relation_data\n    raise ValueError(\nValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1725500474603,"stop":1725500474604,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1725500474604,"stop":1725500474604,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1725500474604,"stop":1725500474754,"duration":150},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1725501365750,"stop":1725501365750,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"abort_on_fail::0","time":{"start":1725501365932,"stop":1725501365932,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1725502116510,"stop":1725502116842,"duration":332},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1725502116842,"stop":1725502116842,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1725502116842,"stop":1725502116842,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1725502116842,"stop":1725502116843,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.new_relations"},{"name":"suite","value":"test_new_relations"},{"name":"host","value":"fv-az1345-708"},{"name":"thread","value":"9366-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.new_relations.test_new_relations"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ee1fa2041fe853d4","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":33,"skipped":1,"passed":54,"unknown":1,"total":89},"items":[{"uid":"69a5c1b0e2006133","reportUrl":"../163//#testresult/69a5c1b0e2006133","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1725414948896,"stop":1725414949018,"duration":122}},{"uid":"b1b91c9014da24bf","reportUrl":"../162//#testresult/b1b91c9014da24bf","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1725328398824,"stop":1725328398962,"duration":138}},{"uid":"71a0c8bcd4b217e9","reportUrl":"../161//#testresult/71a0c8bcd4b217e9","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1725241910033,"stop":1725241910160,"duration":127}},{"uid":"263386c1347a5814","reportUrl":"../160//#testresult/263386c1347a5814","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1725155508644,"stop":1725155508856,"duration":212}},{"uid":"858964ccfc8fed9c","reportUrl":"../159//#testresult/858964ccfc8fed9c","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1725069259580,"stop":1725069259724,"duration":144}},{"uid":"4192b0a32b6a560b","reportUrl":"../158//#testresult/4192b0a32b6a560b","status":"skipped","statusDetails":"XFAIL reason: aborted\n\n_pytest.outcomes.XFailed: aborted","time":{"start":1724982087912,"stop":1724982087912,"duration":0}},{"uid":"1de8956b15ca8edd","reportUrl":"../157//#testresult/1de8956b15ca8edd","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724896229206,"stop":1724896229372,"duration":166}},{"uid":"a243b9071d9048bd","reportUrl":"../156//#testresult/a243b9071d9048bd","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724809938595,"stop":1724809938749,"duration":154}},{"uid":"38fc6dd176779bd2","reportUrl":"../155//#testresult/38fc6dd176779bd2","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724723441036,"stop":1724723441169,"duration":133}},{"uid":"a7192a94688e194a","reportUrl":"../154//#testresult/a7192a94688e194a","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724636995758,"stop":1724636995893,"duration":135}},{"uid":"f981057d0da7e9eb","reportUrl":"../153//#testresult/f981057d0da7e9eb","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724550615923,"stop":1724550616068,"duration":145}},{"uid":"8466484a0c801984","reportUrl":"../152//#testresult/8466484a0c801984","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724464238701,"stop":1724464238846,"duration":145}},{"uid":"98ed7221297a9111","reportUrl":"../151//#testresult/98ed7221297a9111","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724377899517,"stop":1724377899653,"duration":136}},{"uid":"74ed2843ff51678d","reportUrl":"../150//#testresult/74ed2843ff51678d","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724291386239,"stop":1724291386453,"duration":214}},{"uid":"b0fd15fc529fa915","reportUrl":"../149//#testresult/b0fd15fc529fa915","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724205010525,"stop":1724205010708,"duration":183}},{"uid":"7798973fbe0e72dd","reportUrl":"../148//#testresult/7798973fbe0e72dd","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724118898041,"stop":1724118898178,"duration":137}},{"uid":"62eace9e4f220553","reportUrl":"../147//#testresult/62eace9e4f220553","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1724032287492,"stop":1724032287619,"duration":127}},{"uid":"745caf5321f0a5de","reportUrl":"../146//#testresult/745caf5321f0a5de","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1723945872634,"stop":1723945872763,"duration":129}},{"uid":"7a2f3c1526bd53fe","reportUrl":"../145//#testresult/7a2f3c1526bd53fe","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1723859493534,"stop":1723859493670,"duration":136}},{"uid":"26ed9238dcde82c0","reportUrl":"../144//#testresult/26ed9238dcde82c0","status":"broken","statusDetails":"ValueError: no relation data could be grabbed on relation with endpoint first-database and alias None","time":{"start":1723773069067,"stop":1723773069195,"duration":128}}]},"tags":["asyncio","group(1)"]},"source":"f61c3715f4b330f9.json","parameterValues":[]}